source 'https://rubygems.org'

gem 'capybara'
gem 'rspec'
gem 'byebug'
gem 'pry'
gem 'pry-byebug'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'rake'
gem 'report_builder'
gem 'net-smtp'
# gem 'smtp-tls'
# gem 'rubygems'
gem 'mailfactory'
gem 'chilkat'
gem 'html2text'
gem 'json2table'
gem 'json'
